# Generated by Django 4.2.7 on 2025-07-22 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=models.TextField(blank=True, verbose_name='漏洞描述'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='line_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='行号'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='message',
            field=models.TextField(blank=True, verbose_name='原始消息'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='numerical_severity',
            field=models.CharField(blank=True, max_length=4, verbose_name='数值严重程度'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='reporter',
            field=models.CharField(blank=True, max_length=100, verbose_name='报告人'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='scan_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.scantask', verbose_name='扫描任务'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(blank=True, choices=[('Info', 'Info'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Info', max_length=200, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='标签'),
        ),
    ]
