# Generated by Django 4.2.7 on 2025-07-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_finding_description_alter_finding_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='manual_scan',
            field=models.BooleanField(default=False, verbose_name='手动扫描'),
        ),
        migrations.AddField(
            model_name='project',
            name='auto_scan_enabled',
            field=models.BooleanField(default=False, verbose_name='启用自动扫描'),
        ),
        migrations.AddField(
            model_name='project',
            name='git_branch',
            field=models.CharField(default='main', max_length=100, verbose_name='Git分支'),
        ),
        migrations.AddField(
            model_name='project',
            name='git_url',
            field=models.URLField(blank=True, verbose_name='Git仓库地址'),
        ),
        migrations.AddField(
            model_name='scantask',
            name='scan_log',
            field=models.TextField(blank=True, verbose_name='扫描日志'),
        ),
        migrations.AlterField(
            model_name='project',
            name='business_criticality',
            field=models.CharField(blank=True, choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '关键')], default='medium', max_length=20, verbose_name='业务重要性'),
        ),
        migrations.AlterField(
            model_name='project',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展信息'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='tool_name',
            field=models.CharField(choices=[('codeql', 'CodeQL'), ('semgrep', 'Semgrep'), ('sonarqube', 'SonarQube'), ('checkmarx', 'Checkmarx'), ('veracode', 'Veracode'), ('auto', '自动扫描')], max_length=50, verbose_name='扫描工具'),
        ),
    ]
