# Generated by Django 4.2.7 on 2025-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_finding_manual_scan_project_auto_scan_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_branch',
            field=models.CharField(blank=True, default='main', max_length=100, verbose_name='Git分支'),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Git仓库地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='代码仓库'),
        ),
    ]
