# Generated by Django 4.2.7 on 2025-01-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_vulnerability_scoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名称')),
                ('language', models.CharField(choices=[('java', 'Java'), ('javascript', 'JavaScript'), ('python', 'Python'), ('csharp', 'C#'), ('cpp', 'C++'), ('go', 'Go')], max_length=20, verbose_name='编程语言')),
                ('project_type', models.CharField(blank=True, max_length=50, verbose_name='项目类型')),
                ('build_command', models.TextField(verbose_name='编译命令')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '编译配置',
                'verbose_name_plural': '编译配置',
                'ordering': ['language', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='build_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='core.buildconfig', verbose_name='编译配置'),
        ),
    ]