# Generated by Django 4.2.7 on 2025-07-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_build_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(blank=True, choices=[('低危', '低危'), ('中危', '中危'), ('高危', '高危')], default='Info', max_length=200, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_branch',
            field=models.CharField(blank=True, default='master', max_length=100, verbose_name='Git分支'),
        ),
    ]
