# Generated by Django 4.2.7 on 2025-01-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_buildconfig_project_build_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='build_config',
        ),
        migrations.AddField(
            model_name='project',
            name='build_command',
            field=models.TextField(blank=True, help_text='留空使用默认命令', verbose_name='编译命令'),
        ),
        migrations.DeleteModel(
            name='BuildConfig',
        ),
    ]