# Generated by Django 4.2.7 on 2025-01-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_build_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='ai_analyzing',
            field=models.BooleanField(default=False, verbose_name='AI分析中'),
        ),
    ]