# Generated by Django 4.2.7 on 2025-07-29 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_finding_ai_analyzing'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='ai_quality_comment',
            field=models.TextField(blank=True, verbose_name='AI质量评估备注'),
        ),
        migrations.AddField(
            model_name='finding',
            name='ai_quality_rating',
            field=models.CharField(blank=True, choices=[('', '未评估'), ('excellent', '完整正确，可以直接用'), ('good', '建议正确，但是不能直接用'), ('poor', '建议错误')], max_length=20, verbose_name='AI分析质量评级'),
        ),
        migrations.AddField(
            model_name='finding',
            name='ai_rated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='评估时间'),
        ),
        migrations.AddField(
            model_name='finding',
            name='ai_rated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_ratings', to=settings.AUTH_USER_MODEL, verbose_name='评估人'),
        ),
    ]
